name = "payuu-remote-signaling"
main = "index.js"
compatibility_date = "2026-08-23"

[[durable_objects.bindings]]
name = "REMOTE_REGISTRY"
class_name = "RemoteRegistry"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RemoteRegistry"]
